name: Test Api
on: [push, workflow_dispatch]

jobs:
  test-api:
    runs-on: ubuntu-latest
    services:
      app:
        image: greatvand/node-js-api
        ports:
          - 3000:3000
        env:
          MONGO_HOSTNAME: mongo
      mongo:
        image: mongo
        ports:
          - 27017:27017

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install curl
        run: |
          sudo apt-get update
          sudo apt-get install -y curl

      - name: Wait for services
        run: sleep 15   # Wait for Mongo and app to start

      - name: Dump services context
        run: echo '${{ toJson(job.services) }}'

      - name: Post a User
        run: |
          curl -X POST http://localhost:3000/api/users \
          -H "Content-Type: application/json" \
          -d '{"username":"hello","address":"some address"}'

      - name: Get Users
        run: curl http://localhost:3000/api/users
